// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HarvestedLog struct {
	ID          int64              `json:"id"`
	HiveID      int32              `json:"hive_id"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	Severity    string             `json:"severity"`
	SystemdUnit pgtype.Text        `json:"systemd_unit"`
	Component   string             `json:"component"`
	Message     string             `json:"message"`
	RawPayload  []byte             `json:"raw_payload"`
}

type Hive struct {
	ID         int32              `json:"id"`
	Name       string             `json:"name"`
	Hostname   string             `json:"hostname"`
	InitSystem string             `json:"init_system"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
