// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHiveByName = `-- name: GetHiveByName :one
SELECT id, name, hostname, init_system, created_at
FROM hives
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetHiveByName(ctx context.Context, name string) (Hive, error) {
	row := q.db.QueryRow(ctx, getHiveByName, name)
	var i Hive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.InitSystem,
		&i.CreatedAt,
	)
	return i, err
}

const insertHarvestedLog = `-- name: InsertHarvestedLog :exec
INSERT INTO harvested_logs (hive_id, timestamp, severity, systemd_unit, component, message, raw_payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertHarvestedLogParams struct {
	HiveID      int32              `json:"hive_id"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	Severity    string             `json:"severity"`
	SystemdUnit pgtype.Text        `json:"systemd_unit"`
	Component   string             `json:"component"`
	Message     string             `json:"message"`
	RawPayload  []byte             `json:"raw_payload"`
}

func (q *Queries) InsertHarvestedLog(ctx context.Context, arg InsertHarvestedLogParams) error {
	_, err := q.db.Exec(ctx, insertHarvestedLog,
		arg.HiveID,
		arg.Timestamp,
		arg.Severity,
		arg.SystemdUnit,
		arg.Component,
		arg.Message,
		arg.RawPayload,
	)
	return err
}

const listLogsPaged = `-- name: ListLogsPaged :many
SELECT l.id, l.timestamp, l.severity, l.systemd_unit, l.component, l.message, h.name as hive_name
FROM harvested_logs l
JOIN hives h ON l.hive_id = h.id
ORDER BY l.timestamp DESC
LIMIT $1 OFFSET $2
`

type ListLogsPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListLogsPagedRow struct {
	ID          int64              `json:"id"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	Severity    string             `json:"severity"`
	SystemdUnit pgtype.Text        `json:"systemd_unit"`
	Component   string             `json:"component"`
	Message     string             `json:"message"`
	HiveName    string             `json:"hive_name"`
}

func (q *Queries) ListLogsPaged(ctx context.Context, arg ListLogsPagedParams) ([]ListLogsPagedRow, error) {
	rows, err := q.db.Query(ctx, listLogsPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogsPagedRow
	for rows.Next() {
		var i ListLogsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Severity,
			&i.SystemdUnit,
			&i.Component,
			&i.Message,
			&i.HiveName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerHive = `-- name: RegisterHive :one

INSERT INTO hives (name, hostname, init_system)
VALUES ($1, $2, $3)
RETURNING id, name, hostname, init_system, created_at
`

type RegisterHiveParams struct {
	Name       string `json:"name"`
	Hostname   string `json:"hostname"`
	InitSystem string `json:"init_system"`
}

// db/queries.sql
func (q *Queries) RegisterHive(ctx context.Context, arg RegisterHiveParams) (Hive, error) {
	row := q.db.QueryRow(ctx, registerHive, arg.Name, arg.Hostname, arg.InitSystem)
	var i Hive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.InitSystem,
		&i.CreatedAt,
	)
	return i, err
}

const searchLogsByKeyword = `-- name: SearchLogsByKeyword :many
SELECT l.id, l.timestamp, l.severity, l.systemd_unit, l.component, l.message, h.name as hive_name
FROM harvested_logs l
JOIN hives h ON l.hive_id = h.id
WHERE to_tsvector('english', l.message) @@ to_tsquery('english', $1)
ORDER BY l.timestamp DESC
LIMIT $2
`

type SearchLogsByKeywordParams struct {
	ToTsquery string `json:"to_tsquery"`
	Limit     int32  `json:"limit"`
}

type SearchLogsByKeywordRow struct {
	ID          int64              `json:"id"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	Severity    string             `json:"severity"`
	SystemdUnit pgtype.Text        `json:"systemd_unit"`
	Component   string             `json:"component"`
	Message     string             `json:"message"`
	HiveName    string             `json:"hive_name"`
}

func (q *Queries) SearchLogsByKeyword(ctx context.Context, arg SearchLogsByKeywordParams) ([]SearchLogsByKeywordRow, error) {
	rows, err := q.db.Query(ctx, searchLogsByKeyword, arg.ToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchLogsByKeywordRow
	for rows.Next() {
		var i SearchLogsByKeywordRow
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Severity,
			&i.SystemdUnit,
			&i.Component,
			&i.Message,
			&i.HiveName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
