// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	GetHiveByName(ctx context.Context, name string) (Hive, error)
	InsertHarvestedLog(ctx context.Context, arg InsertHarvestedLogParams) error
	ListLogsPaged(ctx context.Context, arg ListLogsPagedParams) ([]ListLogsPagedRow, error)
	// db/queries.sql
	RegisterHive(ctx context.Context, arg RegisterHiveParams) (Hive, error)
	SearchLogsByKeyword(ctx context.Context, arg SearchLogsByKeywordParams) ([]SearchLogsByKeywordRow, error)
}

var _ Querier = (*Queries)(nil)
